class Hashids:
    def __init__(self, salt: str = ..., min_length: int = ..., alphabet: str = ...): ...
    def encode(self, *values: int) -> str: ...
    def decode(self, hashid: str) -> list[int]: ...
    def encode_hex(self, hex_str: str) -> str: ...
    def decode_hex(self, hashid: str) -> str: ...
